### ISSUE TITLE
First Node in Dialogue Tree is Not Vocalized

### ISSUE THREAD

**Issue by willymcgeejr** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#10]
Description: When an NPC interaction is run in a scene, the very first prompt in the tree is not heard by the Scene User.

Replication:
- Run a dialogue tree with at least 1 node and something valid in the prompt field

**Comment by cev092** [comment]
on Start() the dialogueTree script will speak the first prompt.
