### ISSUE TITLE
Prompts in Tree Only Progress on Exact Match

### ISSUE THREAD

**Issue by willymcgeejr** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#12]
Description: Prompts are currently only progressing on exact matches to the given string. Ideally, they would progress so long as the given string was a substring of the full response from the Scene User

**Comment by cev092** [comment]
Changed the string comparison to (string1.tolower() == string2.tolower) instead of (string1 == string2). Case sensitivity is no longer a problem
