### ISSUE TITLE
Nodes in the middle of a tree can be deleted, but all children of the deleted node remain

### ISSUE THREAD

**Issue by willymcgeejr** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#44]
Description: Nodes in the middle of a tree can be deleted, but all children of the deleted node remain in the system, causing creation of further nodes to broken
Reproduction:
- Create a new tree in the tree UI
- Add nodes of depth 2 or greater
- Delete any prompt node with children that have additional prompts
- Creation of new nodes will now be bugged

**Comment by cev092** [comment]
I removed the ability to delete nodes in the middle of a tree, thus preventing the ability to leave stranded nodes.

**Comment by willymcgeejr** [comment]
Resolved in Commit b0339fb to develop
