### ISSUE TITLE
Tree UI scroll bars do not scale with the tree

### ISSUE THREAD

**Issue by willymcgeejr** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#45]
Description: The canvas for tree manipulation in the tree editor does not scale with the tree as it is expanded, preventing you from editing portions of the tree if it gets too wide/deep
Reproduction:
- Create a tree using the tree UI
- Add new nodes until the tree reaches a depth where nodes spill off of the screen
OR
- Add new children to the same node until the tree is too wide to be fully displayed on the screen

**Comment by cev092** [comment]
This is most likely caused by the scrollbar being of type EditorGUILayout, but its contents begin of type EditorGUI.

**Comment by willymcgeejr** [comment]
Resolved in Merge 44cb274 to develop
