### ISSUE TITLE
New trees cannot be modified until they are re-selected in the sidebar

### ISSUE THREAD

**Issue by willymcgeejr** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#46]
Description: When creating a new tree, manipulation of the tree will be locked until you click the new tree's name in the left sidebar
Reproduction:
- Create a new tree in the tree UI
- Any attempt to modify the tree will be locked unless tree is clicked again on left of screen

**Comment by cev092** [comment]
When making a new tree, the new tree will not be selected, and instead the current tree will remain the currently selected tree. I also added a visual to display what is the currently selected tree, which should prevent confusion on which tree is being altered.

**Comment by willymcgeejr** [comment]
Resolved by Commit b0339fb in develop
