### ISSUE TITLE
Creation of new nodes causes visual bug in node contents

### ISSUE THREAD

**Issue by willymcgeejr** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#47]
Description: Creation of a new node will sometimes cause the contents of other nodes to display incorrectly, while the underlying data remains correct
Reproduction:
- Creating a new node (n+1) with values in the rest of the tree will visually bug the second last node (n-1) that was created with the string from the last created node (n) for nodes added at or beyond depth 3

**Comment by cev092** [comment]
Before making a new node, the current selected text field is deselected, this prevents the contents of other nodes to change when a new node is created.

**Comment by willymcgeejr** [comment]
Resolved by Commit b342ecf in develop
