### ISSUE TITLE
custom gui and data persistence

### ISSUE THREAD

**Issue by CompSci0404** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#61]
Found a new bug recently, where the tree that was originally built in a separate scene cannot be transferred to another scene. It loses its references to the dialogue files. The files are not connected within the tree, however, the dialogue object file still exists it is just not hooked up correctly.

**Comment by willymcgeejr** [comment]
Resolved in Merge 1a897cb to develop
