### ISSUE TITLE
GUI Window Becomes Inaccessible on Drag

### ISSUE THREAD

**Issue by willymcgeejr** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#70]
Description: The custom GUI window can be obscured enough that the only way to access it is to close and re-open Unity

Reproduction: If the custom GUI is opened in Unity, then the window is dragged off screen, it cannot be retrieved again without restarting.

**Comment by cev092** [comment]
Unity is handling the dragging of the customGUI the same as it would any other inspector tool. Other Unity inspector tools (for example "service") can also be dragged off screen and become unobtainable until Unity is closed and reopened. As a result, I'm not sure if this can be fixed, but I will look into it

**Comment by willymcgeejr** [comment]
No worries, we had a discussion about this yesterday during the bug party. See if there's maybe a way to have it "re-center" whenever customGUI is chosen from the Window tab. Otherwise, just let me know if it's not possible and I'll mark and close this issue accordingly
