### ISSUE TITLE
No Resolution for Hitting Leaf of Dialogue Tree

### ISSUE THREAD

**Issue by willymcgeejr** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#71]
Description: Null pointer exception is triggered when the end of a tree is reached when running in the scene. Instead, this situation should cause the scene to display an Interaction Complete message and (possibly) display the log.

Reproduction:
- Run a scene with a dialogue tree that has more than one node
- Navigate through the tree until you hit a node with no more children
- Exception will be triggered

**Comment by ineedbots** [comment]
Duplicate of #113
