### ISSUE TITLE
KMPcomp does nothing

### ISSUE THREAD

**Issue by syncrotron** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-1#84]
Well going through the code for the state diagram, KMPcomp within LangaugeEngine.cs appears to always return 1, regardless of the actual algorithm in KMPcomp. I also have confirmed it is not passed by reference or within the passed in list.

**Comment by KareemOluwaseyi** [comment]
Yeah the implementation using KMP isn’t complete, it returns 1 by default for now just for testing purposes.

**Comment by ineedbots** [comment]
Commit c837124b5855e48db4b92bdc04b19c1638461935 addresses this
